[env]
TERM = "screen-256color"

[window]
dimensions = { columns = 120, lines = 30 }
padding = { x = 8, y = 8 }
dynamic_padding = true
decorations = "full"
#opacity = 0.95
#blur = true
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true
class = { instance = "Alacritty", general = "Alacritty" }

[scrolling]
history = 10000
multiplier = 3

[font]
size = 12.0
#normal = { family = "CaskaydiaCove Nerd Font", style = "SemiLight" }
#bold = { family = "CaskaydiaCove Nerd Font", style = "SemiBold" }
#italic = { family = "CaskaydiaCove Nerd Font", style = "Italic" }
#bold_italic = { family = "CaskaydiaCove Nerd Font", style = "Bold Italic" }
normal = { family = "Cascadia Code NF", style = "Regular" }
bold = { family = "Cascadia Code NF", style = "Bold" }
italic = { family = "Cascadia Code NF", style = "Italic" }
bold_italic = { family = "Cascadia Code NF", style = "Bold Italic" }
#normal = { family = "Consolas", style = "Regular" }
#bold = { family = "Consolas", style = "Bold" }
#italic = { family = "Consolas", style = "Italic" }
#bold_italic = { family = "Consolas", style = "Bold Italic" }

# normal = { family = "Cascadia Code", style = "Regular" }
# normal = { family = "Fira Code", style = "Regular" }
# normal = { family = "Source Code Pro", style = "Regular" }
# normal = { family = "Consolas", style = "Regular" }

# modified Tokyo Night color scheme
[colors]
primary = { background = "#16161e", foreground = "#c0caf5" }
normal = { black = "#15161e", red = "#f7768e", green = "#9ece6a", yellow = "#e0af68", blue = "#7aa2f7", magenta = "#bb9af7", cyan = "#7dcfff", white = "#a9b1d6" }
bright = { black = "#414868", red = "#f7768e", green = "#9ece6a", yellow = "#e0af68", blue = "#7aa2f7", magenta = "#bb9af7", cyan = "#7dcfff", white = "#c0caf5" }
cursor = { text = "#1a1b26", cursor = "#c0caf5" }
vi_mode_cursor = { text = "#1a1b26", cursor = "#bb9af7" }
selection = { text = "CellForeground", background = "#33467c" }
search = { matches = { foreground = "#1a1b26", background = "#e0af68" }, focused_match = { foreground = "#1a1b26", background = "#f7768e" } }
hints = { start = { foreground = "#1a1b26", background = "#e0af68" }, end = { foreground = "#e0af68", background = "#1a1b26" } }

[bell]
animation = "EaseOutExpo"
duration = 0
color = "#ffffff"
command = "None"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 750
unfocused_hollow = true
thickness = 0.15

[terminal]
shell = { program = "wsl", args = ["~"] }
osc52 = "CopyPaste"

[mouse]
hide_when_typing = true
bindings = [
    { mouse = "Right", action = "PasteSelection" },
    { mouse = "Middle", action = "PasteSelection" },
]

[hints]
enabled = [
    { regex = "(gemini:|https:|http:|file:|git:)[^\\u0000-\\u001f\\u007f-\\u009f<>\"\\s{-}\\^⟨⟩`]+", hyperlinks = true, command = "xdg-open", post_processing = true, mouse = { enabled = true, mods = "None" }, binding = { key = "U", mods = "Control|Shift" } }
]

#[debug]
#render_timer = false
#persistent_logging = false
#log_level = "Warn"
#print_events = false
#highlight_damage = false
#prefer_egl = false
